app/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views, viewsPaciente
app_name='app'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path(r'personas/', views.PersonasView.as_view(), name='personas'),
    path('usuario/create/', views.UsuarioCreate, name='usuarioCreate'),
    path(r'citas/', views.CitasView.as_view(), name='citaList'),
    url(r'^citas/create/$', views.citas_create, name='citaCreate'),
    url(r'^citas/view/$', views.citas_paciente, name='citasPaciente'),


    #aris
    path('registroConsulta/',views.consulta,name='verconsulta'),
    path('guardarConsulta/',views.guardarconsulta,name='guardarconsulta'),
    path('listarConsulta/',views.listarConsulta,name='listarConsulta'),
    path('detalleConsulta/<int:id_conultamedica>/',views.detalleConsulta,name='detalleconsulta'),
    path('editarConsulta/<int:id_conultamedica>/',views.editarConsulta,name='editarconsulta'),
    path('listarCirugia/',views.listarCirugia,name='listarcirugia'),
    path('verCirugia/<int:id_conultamedica>/',views.verCirugia,name='vercirugia'),
    path('editarCirugia/<int:id_conultamedica>/',views.editarCirugia,name='detallecirugia'),
    path('DetalleCirugia/<int:id_conultamedica>/',views.detallarCirugia,name='detallarcirugia'),
    path('eliminarConsulta/<int:id_conultamedica>/',views.eliminarConsulta,name='eliminarconsulta'),
    path('eliminarCirugia/<int:id_conultamedica>/',views.eliminarCirugia,name='eliminarcirugia'),
    path('IngresoHospitalario/',views.ingresoHospitalarioCreate,name='ingresoHospitalario'),
    path('IngresoHospitalario/guardar/',views.guardarIngresoHospitalario,name='guardarIngresoHospitalario'),
    path('IngresoHospitalario/Listar/',views.listIngresoHospitalario,name='listarIngresoHospitalario'),
    path('IngresoHospitalario/Detalle/<int:id_ingresohospitalario2>/',views.detalleIngresoHopsitalario,name='detalleIngresoHospitalario'),
    path('IngresoHospitalario/Editar/<int:id_ingresohospitalario2>/',views.editIngresoHospitalario,name='EditarIngresoHospitalario'),
    path('IngresoHospitalario/AltaMedica/<int:id_ingresohospitalario2>/',views.altaMedica,name='AltaMedica'),
    path('IngresoServicioHospitalario/Buscar/',views.BuscarIngresoServicioHospitalario,name='BuscarIngresoHospitalario'),
    path('ServicioHospitalario/Create/<int:id_ingresohospitalario2>/',views.CreateServicioHospitalario,name='crearServicioHospitalario'),
    path('ServicioHospitalario/Listar/',views.ListarServiciosHospitalarios,name='listarServicioHospitalario'),
    path('ServicioHospitalario/editar/<int:id_servicio_hospitalario>/',views.EditarServicioHospitalario,name='editarServicioHospitalario'),
    path('ServicioHospitalario/eliminar/<int:id_servicio_hospitalario>/',views.EliminarServicioHospitalario,name='eliminarServicioHospitalario'),
    path('Examen/Buscar/',views.ListarExamenMedico,name='buscarExamen'),
    path('Examen/IngresarReultado/<int:id_examen>/',views.upload_file,name='subirArchivo'),
    path('Examen/editar/<int:id_adjunto>/',views.post_edit,name='editarArchivo'),
    path('Examen/Realizado/<int:id_examen>/',views.ExamenRealizado,name='ExamenRealizado'),
    path('Examen/Historial/',views.ExamenesHistoricos,name='HistorialExamen'),
    path('Examen/Historial/<int:id_examen>/',views.VistaDeArchivosHistoricos,name='HistorialExamen'),
    path('Examen/Resultados/<int:id_examen>/',views.IngresarDatosDeResultadoExamen,name='ResultadoExamen'),
    path('Examen/Datos/Historial/<int:id_examen>/',views.ListarDatosExamenesHistoricos,name='ListarDatosExamen'),
    url(r'^Examen/Resultado/view/$', views.ResultadosExamenesView, name='resultadoview'),
    url(r'^Examen/Archivos/view/$', views.ArchivosModalesView, name='archivosview'),
    path('SignoVital/BuscarPaciente/',views.BuscarPacienteSignoVital,name='BuscarPacienteSignoVital'),
    path('SignoVital/Ingresar/<int:id_paciente>/',views.CrearSignoVital,name='crearSignoVital'),
    path('SignoVital/Editar/<int:id_paciente>/',views.EditarSignoVital,name='EditarSignoVital'),
    path('SignoVital/Eliminar/<int:id_paciente>/',views.EliminarSignoVital,name='EliminarSignoVital'),
    path('SignoVital/Historial/',views.BuscarSignoVitalHistorico,name='HistoricoSignoVital'),
    path('SignoVital/Detalle/<int:id_signovital2>/',views.VerHistorialSignoVital,name='DetalleHistoricoSignoVital'),

    #aris
    #patty
    path('seguimientoCirugia/<int:id_conultamedica>/',views.seguimientoCirugia,name="guardarCirugia"),
    path('seguimientoCirugia/', views.guardarSegCirugia, name="guardarSeguimiento"),
    path('seguimientoLista/', views.listarSeguimientos, name="listarSeguimientosCirugias"),
    path('seguimientoLista/<int:id_cirugia2>', views.seguimiento, name="listadoseguimiento"),
    path('editarSeguimiento/<int:id_postoperacion2>/',views.editarSeguimiento,name='editarSeguimiento'),
    path('Examen/Crear/', views.AsignarExamenMedico, name="AsignarExamenMedico"),
    path('examen/Asignacion/<int:id_conultamedica>/',views.AsignarExamenAPacietne,name='AsignarAPaceinte'),
    path('Examen/Activos/<int:id_conultamedica>/',views.ListarExamenesActivos,name='ExamenesActivos'),
    path('Examen/Eliminar/<int:id_examen>/',views.EliminarExamenActivo,name='EliminarExamenesActivos'),

    path('tratamientoLista/',views.tratamientoConsulta,name='listarConsultaTratamiento'),
    path('asignarTratamiento/', views.guardarAsignacionTratamiento, name="guardarTratamiento"),
    path('asignarTratamiento/<int:id_conultamedica>/',views.tratamientoAsignacion,name="guardarTratamientoAsignacion"),
    path('tratamientos/<int:id_conultamedica>/',views.tratamientosAsignados,name="listarTratamientos"),
    path('editarTratamiento/<int:id_tratamiento2>/',views.editarTratamientos,name="editarTrat"),
    path('eliminarTratamiento/<int:id_tratamiento2>/',views.eliminarTratamiento,name="eliminarTratamiento"),
    #patty

    path('paciente/detalle', viewsPaciente.indexPaciente, name='pacienteList'),
    path('paciente/buscar', viewsPaciente.buscarPaciente, name='pacienteBuscar'),
    path('paciente/agregar', viewsPaciente.agregarPaciente, name='pancienteAgregar'),
    path('paciente/listar', viewsPaciente.listPaciente, name='pancienteListar'),
    path('paciente/save', viewsPaciente.savePaciente, name='pancienteSave'),
    path('paciente/familiares/<int:paciente_id>', viewsPaciente.parientesIndex, name='parientes'),
    path('paciente/familiares/save', viewsPaciente.parientesSave, name='parienteSave'),
    path('paciente/historial/<int:paciente_id>', viewsPaciente.historialIndex, name ='historialIndex'),  #url de menu?
    path('paciente/historial/update', viewsPaciente.historialUpdate, name='historialUpdate'),
    path('serviciohospitalario/bitacora/<int:serv_id>', viewsPaciente.bitacoraIndex, name='bitacoraIndex'),
	path('serviciohospitalario/bitacora/save', viewsPaciente.bitacoraSave, name='bitacoraSave'),
    path('serviciohospitalario/bitacora/update/', viewsPaciente.bitacoraUpdate, name='bitacoraUpdate'),
]

expedienteClinico/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    url('accounts/', include('django.contrib.auth.urls')),
]

app/templates/app/Cirugia/editarCirugia.html
{% extends "app/base_template.html" %}

{% block content %}




     <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="pull-left page-title">Edición de Cirugías </h4>

                            </div>
                        </div>





                        <!-- Form-validation -->
                        <div class="row">

                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Editar Cirugía</h3></div>
                                    <div class="panel-body">
                                        <div class=" form">

                                               {% if cirugia and dcirugia %}
                                                    <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="{% url 'app:detallecirugia' cirugia.id_conultamedica.id_conultamedica %}" novalidate="novalidate">
                                                {% csrf_token %}
                                                <div class="form-group ">
                                                    <label for="npa" class="control-label col-lg-2">Nombre de la Cirugía: </label>
                                                    <div class="col-lg-10">
                                                        <input readonly="readonly" class=" form-control" id="" name="" type="text" value="{{ cirugia.id_catalogo.catalogo }}" >
                                                        <input readonly="readonly" class=" form-control" id="ncirugia" name="ncirugia" type="hidden" value="{{ cirugia.id_catalogo.codigo }}" >

                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="descripcion" class="control-label col-lg-2">Descripción de la Cirugía:</label>
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3" id="descripcion" name="descripcion" maxlength="200">{{ dcirugia.descripcion }}</textarea>
                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="nmed" class="control-label col-lg-2">Nombre del Paciente:</label>
                                                    <div class="col-lg-10">
                                                        <input type="text" class="form-control" value="{{ cirugia.id_conultamedica.id_paciente.id_persona.nombre }} {{ cirugia.id_conultamedica.id_paciente.id_persona.apellido }}" id="" name="" readonly="readonly">
                                                        <input type="hidden" class="form-control" value="{{ cirugia.id_conultamedica.id_paciente.id_paciente }}" id="npa" name="npa" readonly="readonly" hidden="hidden">
                                                    </div>
                                                </div>



                                                <div class="form-group ">
                                                    <label for="fecha" class="control-label col-lg-2">Fecha de la Cirugía:</label>

                                                        <div class="col-lg-10">
                                                            <input type="date" class="form-control" value="{{ cirugia.fecha_programada.isoformat }}" id="" name="fecha" >
                                                       </div>
                                                </div>


                                                         <div class="form-group ">
                                                    <label for="fecha" class="control-label col-lg-2">Hora:</label>

                                                        <div class="col-lg-10">
                                                            <input type="time" class="form-control" value="{{ cirugia.hora}}" id="" name="hora" >
                                                       </div>
                                                </div>

                                                         <div class="form-group ">
                                                    <label for="descripcion" class="control-label col-lg-2">Procedimiento de la Cirugía:</label>
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3" id="Pcirugia" name="Pcirugia" maxlength="200">{{ dcirugia.procedimiento }}</textarea>
                                                         {% if confirm_message %}<p><strong><h3 class="label label-success">{{ confirm_message }}</h3></strong></p>{% endif %}
                                                    </div>
                                                </div>




                                                     <div class="form-group">
                                                    <div class="col-lg-offset-2 col-lg-10">
                                                        <button class="btn btn-success waves-effect waves-light" type="submit">Enviar</button>

                                                    </div>
                                                </div>
                                                    </form>
                                            {% elif cirugia %}

                                                   <form class="cmxform form-horizontal tasi-form" id="signupForm" method="post" action="{% url 'app:detallecirugia' cirugia.id_conultamedica.id_conultamedica %}" novalidate="novalidate">
                                                {% csrf_token %}
                                                <div class="form-group ">
                                                    <label for="npa" class="control-label col-lg-2">Nombre de la Cirugía: </label>
                                                    <div class="col-lg-10">
                                                        <input readonly="readonly" class=" form-control" id="" name="" type="text" value="{{ cirugia.id_catalogo.catalogo }}" >
                                                        <input readonly="readonly" class=" form-control" id="ncirugia" name="ncirugia" type="hidden" value="{{ cirugia.id_catalogo.codigo }}" >

                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="descripcion" class="control-label col-lg-2">Descripción de la Cirugía:</label>
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3" id="descripcion" name="descripcion" maxlength="200"></textarea>
                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="npa" class="control-label col-lg-2">Nombre del Paciente:</label>
                                                    <div class="col-lg-10">
                                                        <input type="text" class="form-control" placeholder="{{ cirugia.id_conultamedica.id_paciente.id_persona.nombre }} {{ cirugia.id_conultamedica.id_paciente.id_persona.apellido }}" id="" name="" readonly="readonly">
                                                        <input type="hidden" class="form-control" value="{{ cirugia.id_conultamedica.id_paciente.id_paciente }}" id="npa" name="npa" readonly="readonly">
                                                    </div>
                                                </div>



                                                <div class="form-group ">
                                                    <label for="fecha" class="control-label col-lg-2">Fecha de la Cirugía:</label>

                                                        <div class="col-lg-10">
                                                            <input type="date" class="form-control" value="{{ cirugia.fecha_programada.isoformat }}" id="fecha" name="fecha" value="">
                                                       </div>
                                                </div>

                                                        <div class="form-group ">
                                                    <label for="hora" class="control-label col-lg-2">Hora:</label>

                                                        <div class="col-lg-10">
                                                            <input type="time" class="form-control" value="{{ cirugia.hora }}" id="" name="hora" >
                                                       </div>
                                                </div>

                                                         <div class="form-group ">
                                                    <label for="Pcirugia" class="control-label col-lg-2">Procedimiento de la Cirugía:</label>
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3" id="Pcirugia" name="Pcirugia" maxlength="200"></textarea>

                                                    </div>
                                                </div>




                                                     <div class="form-group">
                                                    <div class="col-lg-offset-2 col-lg-10">
                                                        <button class="btn btn-success waves-effect waves-light" type="submit">Enviar</button>

                                                    </div>
                                                </div>
                                                    </form>
                                            {% endif %}





                                        </div> <!-- .form -->

                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->



            </div> <!-- container -->

                </div> <!-- content -->



            </div>





{% endblock %}

app/templates/app/Cirugia/listarCirugia.html
{% extends "app/base_template.html" %}


{% block content %}


    <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="pull-left page-title">Busqueda de Cirugías </h4>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Buscar Cirugía</h3></div>
                                    <div class="panel-body">
                                        <div class=" form">
                                            <form class="cmxform form-horizontal tasi-form" id="commentForm" method="post" action="{% url 'app:listarcirugia' %}" >
                                                {% csrf_token %}
                                                <div class="form-group ">
                                                    <label for="npaciente" class="control-label col-lg-2">Expediente del Paciente:</label>
                                                    <div class="col-lg-10">
                                                        <input  class="form-control" id="epaciente" name="epaciente" type="text" >

                                                    </div>
                                                </div>
                                             <div class="form-group ">
                                                    <label for="fecha" class="control-label col-lg-2">Fecha de la Consulta:</label>

                                                        <div class="col-lg-10">
                                                          <input type="date" class="form-control" value="dd-mm-aaaa" id="fecha" name="fecha" >

                                                        </div>
                                                </div>


                                            <div class="form-group ">
                                                <label for="nmed" class="control-label col-lg-2">Tipo de Cirugía:</label>
                                                  <div class="col-lg-10">
                                                      <select name="tcirugia" class="form-control" >
                                                          <option value=''>Elija Tipo Cirugia</option>
                                                             {% for cirus in ciru %}
                                                                 <option value="{{ cirus.codigo }}">{{ cirus.catalogo }}</option>
                                                             {% endfor %}
                                                      </select>
                                                  <br>
                                                            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                                                  </div>
                                            </div>





                                                <div class="form-group">
                                                    <div class="col-lg-offset-2 col-lg-10">
                                                        <button class="btn btn-success waves-effect waves-light" type="submit">Buscar</button>

                                                    </div>
                                                </div>
                                            </form>
                                        </div> <!-- .form -->
                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->


                        <!-- Form-validation -->
                        <div class="row">

                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Datos de la Cirugía</h3></div>
                                    <div class="panel-body">

                                        {% if cirugia%}
                                    <table class="table">
                                      <thead>
                                        <tr>
                                          <th scope="col">Tipo de Cirugía</th>
                                          <th scope="col">Id Consulta Médica</th>
                                          <th scope="col">Fecha de Emisión</th>
                                            <th scope="col">Opciones</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      {% for cirugias in cirugia %}
                                        <tr>
                                         <th scope="row">{{  cirugias.id_catalogo.catalogo }}</th>

                                         <td>{{ cirugias.id_conultamedica.id_conultamedica}}</td>

                                         <td>{{  cirugias.id_conultamedica.fecha_consulta}}</td>
                                         <td>

                                                        <a href="{% url 'app:detallarcirugia' cirugias.id_conultamedica.id_conultamedica %}" ><span class="label label-success">ver</span></a>
                                                        <a href="{% url 'app:vercirugia' cirugias.id_conultamedica.id_conultamedica %}"><span class="label label-warning">Editar</span></a>
                                                        <a href="{% url 'app:guardarCirugia' cirugias.id_conultamedica.id_conultamedica %}"><span class="label label-purple">Seguimientos</span></a>
                                                        <a href="{% url 'app:eliminarcirugia' cirugias.id_conultamedica.id_conultamedica %}" onclick="return confirm('Desea Eliminar la Cirugia')"><span class="label label-danger">Eliminar</span></a>



                                         </td>
    </tr>
                                      {% endfor %}

  </tbody>
</table>
                                        {% else %}
                                                              <table class="table">
                                      <thead>
                                        <tr>
                                          <th scope="col">Tipo de Cirugía</th>
                                          <th scope="col">Id Consulta Médica</th>
                                          <th scope="col">Fecha</th>
                                            <th scope="col">Opciones</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                         <th scope="row">Nombre Cirugía</th>
                                         <td>Id</td>
                                         <td>Fecha Consulta</td>

    </tr>

  </tbody>
</table>




                                        {% endif %}

                                        </div> <!-- .form -->

                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->



            </div> <!-- container -->

                </div> <!-- content -->



            </div>


{% endblock %}