app/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views, viewsPaciente
app_name='app'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path(r'personas/', views.PersonasView.as_view(), name='personas'),
    path('usuario/create/', views.UsuarioCreate, name='usuarioCreate'),
    path(r'citas/', views.CitasView.as_view(), name='citaList'),
    url(r'^citas/create/$', views.citas_create, name='citaCreate'),
    url(r'^citas/view/$', views.citas_paciente, name='citasPaciente'),


    #aris
    path('registroConsulta/',views.consulta,name='verconsulta'),
    path('guardarConsulta/',views.guardarconsulta,name='guardarconsulta'),
    path('listarConsulta/',views.listarConsulta,name='listarConsulta'),
    path('detalleConsulta/<int:id_conultamedica>/',views.detalleConsulta,name='detalleconsulta'),
    path('editarConsulta/<int:id_conultamedica>/',views.editarConsulta,name='editarconsulta'),
    path('listarCirugia/',views.listarCirugia,name='listarcirugia'),
    path('verCirugia/<int:id_conultamedica>/',views.verCirugia,name='vercirugia'),
    path('editarCirugia/<int:id_conultamedica>/',views.editarCirugia,name='detallecirugia'),
    path('DetalleCirugia/<int:id_conultamedica>/',views.detallarCirugia,name='detallarcirugia'),
    path('eliminarConsulta/<int:id_conultamedica>/',views.eliminarConsulta,name='eliminarconsulta'),
    path('eliminarCirugia/<int:id_conultamedica>/',views.eliminarCirugia,name='eliminarcirugia'),
    path('IngresoHospitalario/',views.ingresoHospitalarioCreate,name='ingresoHospitalario'),
    path('IngresoHospitalario/guardar/',views.guardarIngresoHospitalario,name='guardarIngresoHospitalario'),
    path('IngresoHospitalario/Listar/',views.listIngresoHospitalario,name='listarIngresoHospitalario'),
    path('IngresoHospitalario/Detalle/<int:id_ingresohospitalario2>/',views.detalleIngresoHopsitalario,name='detalleIngresoHospitalario'),
    path('IngresoHospitalario/Editar/<int:id_ingresohospitalario2>/',views.editIngresoHospitalario,name='EditarIngresoHospitalario'),
    path('IngresoHospitalario/AltaMedica/<int:id_ingresohospitalario2>/',views.altaMedica,name='AltaMedica'),
    path('IngresoServicioHospitalario/Buscar/',views.BuscarIngresoServicioHospitalario,name='BuscarIngresoHospitalario'),
    path('ServicioHospitalario/Create/<int:id_ingresohospitalario2>/',views.CreateServicioHospitalario,name='crearServicioHospitalario'),
    path('ServicioHospitalario/Listar/',views.ListarServiciosHospitalarios,name='listarServicioHospitalario'),
    path('ServicioHospitalario/editar/<int:id_servicio_hospitalario>/',views.EditarServicioHospitalario,name='editarServicioHospitalario'),
    path('ServicioHospitalario/eliminar/<int:id_servicio_hospitalario>/',views.EliminarServicioHospitalario,name='eliminarServicioHospitalario'),
    path('Examen/Buscar/',views.ListarExamenMedico,name='buscarExamen'),
    path('Examen/IngresarReultado/<int:id_examen>/',views.upload_file,name='subirArchivo'),
    path('Examen/editar/<int:id_adjunto>/',views.post_edit,name='editarArchivo'),
    path('Examen/Realizado/<int:id_examen>/',views.ExamenRealizado,name='ExamenRealizado'),
    path('Examen/Historial/',views.ExamenesHistoricos,name='HistorialExamen'),
    path('Examen/Historial/<int:id_examen>/',views.VistaDeArchivosHistoricos,name='HistorialExamen'),
    path('Examen/Resultados/<int:id_examen>/',views.IngresarDatosDeResultadoExamen,name='ResultadoExamen'),
    path('Examen/Datos/Historial/<int:id_examen>/',views.ListarDatosExamenesHistoricos,name='ListarDatosExamen'),
    url(r'^Examen/Resultado/view/$', views.ResultadosExamenesView, name='resultadoview'),
    url(r'^Examen/Archivos/view/$', views.ArchivosModalesView, name='archivosview'),
    path('SignoVital/BuscarPaciente/',views.BuscarPacienteSignoVital,name='BuscarPacienteSignoVital'),
    path('SignoVital/Ingresar/<int:id_paciente>/',views.CrearSignoVital,name='crearSignoVital'),
    path('SignoVital/Editar/<int:id_paciente>/',views.EditarSignoVital,name='EditarSignoVital'),
    path('SignoVital/Eliminar/<int:id_paciente>/',views.EliminarSignoVital,name='EliminarSignoVital'),
    path('SignoVital/Historial/',views.BuscarSignoVitalHistorico,name='HistoricoSignoVital'),
    path('SignoVital/Detalle/<int:id_signovital2>/',views.VerHistorialSignoVital,name='DetalleHistoricoSignoVital'),

    #aris
    #patty
    path('seguimientoCirugia/<int:id_conultamedica>/',views.seguimientoCirugia,name="guardarCirugia"),
    path('seguimientoCirugia/', views.guardarSegCirugia, name="guardarSeguimiento"),
    path('seguimientoLista/', views.listarSeguimientos, name="listarSeguimientosCirugias"),
    path('seguimientoLista/<int:id_cirugia2>', views.seguimiento, name="listadoseguimiento"),
    path('editarSeguimiento/<int:id_postoperacion2>/',views.editarSeguimiento,name='editarSeguimiento'),
    path('Examen/Crear/', views.AsignarExamenMedico, name="AsignarExamenMedico"),
    path('examen/Asignacion/<int:id_conultamedica>/',views.AsignarExamenAPacietne,name='AsignarAPaceinte'),
    path('Examen/Activos/<int:id_conultamedica>/',views.ListarExamenesActivos,name='ExamenesActivos'),
    path('Examen/Eliminar/<int:id_examen>/',views.EliminarExamenActivo,name='EliminarExamenesActivos'),

    path('tratamientoLista/',views.tratamientoConsulta,name='listarConsultaTratamiento'),
    path('asignarTratamiento/', views.guardarAsignacionTratamiento, name="guardarTratamiento"),
    path('asignarTratamiento/<int:id_conultamedica>/',views.tratamientoAsignacion,name="guardarTratamientoAsignacion"),
    path('tratamientos/<int:id_conultamedica>/',views.tratamientosAsignados,name="listarTratamientos"),
    path('editarTratamiento/<int:id_tratamiento2>/',views.editarTratamientos,name="editarTrat"),
    path('eliminarTratamiento/<int:id_tratamiento2>/',views.eliminarTratamiento,name="eliminarTratamiento"),
    #patty

    path('paciente/detalle', viewsPaciente.indexPaciente, name='pacienteList'),
    path('paciente/buscar', viewsPaciente.buscarPaciente, name='pacienteBuscar'),
    path('paciente/agregar', viewsPaciente.agregarPaciente, name='pancienteAgregar'),
    path('paciente/listar', viewsPaciente.listPaciente, name='pancienteListar'),
    path('paciente/save', viewsPaciente.savePaciente, name='pancienteSave'),
    path('paciente/familiares/<int:paciente_id>', viewsPaciente.parientesIndex, name='parientes'),
    path('paciente/familiares/save', viewsPaciente.parientesSave, name='parienteSave'),
    path('paciente/historial/<int:paciente_id>', viewsPaciente.historialIndex, name ='historialIndex'),  #url de menu?
    path('paciente/historial/update', viewsPaciente.historialUpdate, name='historialUpdate'),
    path('serviciohospitalario/bitacora/<int:serv_id>', viewsPaciente.bitacoraIndex, name='bitacoraIndex'),
	path('serviciohospitalario/bitacora/save', viewsPaciente.bitacoraSave, name='bitacoraSave'),
    path('serviciohospitalario/bitacora/update/', viewsPaciente.bitacoraUpdate, name='bitacoraUpdate'),
]

expedienteClinico/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    url('accounts/', include('django.contrib.auth.urls')),
]

app/templates/app/ingresoHospitalario/AsignacionServicioHospitalario.html
{% extends "app/base_template.html" %}


{% block content %}


    <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="pull-left page-title">Ingresar Servicio Hospitalario </h4>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Buscar Ingreso Hospitalario</h3></div>
                                    <div class="panel-body">
                                        <div class=" form">
                                            <form class="cmxform form-horizontal tasi-form"  method="POST" action="{% url 'app:BuscarIngresoHospitalario' %}" >
                                                {% csrf_token %}
                                                <div class="form-group ">
                                                    <label for="hpaciente" class="control-label col-lg-2">Expediente del Paciente:</label>
                                                    <div class="col-lg-10">
                                                        <input  class="form-control"  id="hpaciente" name="hpaciente" type="text" maxlength="25" required>
                                                    <br>
                                                         {% if error_message %}<p ><strong ><h3 class="label label-danger" >{{ error_message }}</h3></strong></p>{% endif %}
                                                    </div>
                                                </div>


                                                <div class="form-group">
                                                    <div class="col-lg-offset-2 col-lg-10">
                                                        <button class="btn btn-success waves-effect waves-light" type="submit">Buscar</button>

                                                    </div>
                                                </div>
                                            </form>
                                        </div> <!-- .form -->
                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->


                        <!-- Form-validation -->
                        <div class="row">

                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Datos del Ingreso Hospitalario</h3></div>
                                    <div class="panel-body">

                                        {% if ingreso%}
                                    <table class="table">
                                      <thead>
                                        <tr>
                                           <th scope="col">Nombre del Paciente</th>
                                          <th scope="col">Fecha de Ingreso Hopitalario</th>
                                          <th scope="col">Doctor Encargado</th>

                                            <th scope="col">Opciones</th>
                                        </tr>
                                      </thead>
                                      <tbody>

                                        <tr>
                                         <th scope="row">{{ ingreso.id_paciente.id_persona.nombre}} {{ ingreso.id_paciente.id_persona.apellido}}</th>
                                         <td>{{ ingreso.fecha_ingreso}}</td>
                                         <td>{{ ingreso.id_medico.id_persona.nombre}} {{ ingreso.id_medico.id_persona.apellido}}</td>

                                         <td>

                                                        <a href="{% url 'app:crearServicioHospitalario' ingreso.id_ingresohospitalario2 %}" ><span class="label label-success">Ingresar</span></a>





                                         </td>
    </tr>


  </tbody>
</table>
                                        {% else %}
                                                              <table class="table">
                                      <thead>
                                        <tr>
                                          <th scope="col">Nombre del Paciente</th>
                                          <th scope="col">Fecha de Ingreso Hopitalario</th>
                                          <th scope="col">Doctor Encargado</th>
                                            <th scope="col">Tipo de ingreso</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                         <th scope="row">No hay registros</th>


                                        </tr>

                                       </tbody>
                                </table>




                                        {% endif %}

                                        </div> <!-- .form -->

                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->



            </div> <!-- container -->

                </div> <!-- content -->



            </div>


{% endblock %}

app/templates/app/ingresoHospitalario/GestionarIngresoHospitalario.html
{% extends "app/base_template.html" %}


{% block content %}


    <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="pull-left page-title">Busqueda de Ingresos Hospitalarios </h4>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Buscar Ingreso Hospitalario</h3></div>
                                    <div class="panel-body">
                                        <div class=" form">
                                            <form class="cmxform form-horizontal tasi-form"  method="POST" action="{% url 'app:listarIngresoHospitalario' %}" >
                                                {% csrf_token %}
                                                <div class="form-group ">
                                                    <label for="hpaciente" class="control-label col-lg-2">Expediente del Paciente:</label>
                                                    <div class="col-lg-10">
                                                        <input  class="form-control"  id="hpaciente" name="hpaciente" type="text" maxlength="25">
                                                    </div>
                                                </div>
                                             <div class="form-group ">
                                                    <label for="hfecha" class="control-label col-lg-2">Fecha del Ingreso Hospitalario:</label>

                                                        <div class="col-lg-10">
                                                          <input type="date" class="form-control" value="dd-mm-aaaa"  name="hfecha" >

                                                        </div>
                                                </div>


                                            <div class="form-group ">
                                                <label for="alta" class="control-label col-lg-2">Ingresos Dados de Alta:</label>
                                                  <div class="col-lg-3">
                                                     <select name="alta" class="form-control" >
                                                          <option value=''>Selecciones Una Opción</option>
                                                                 <option value="s">Activo</option>
                                                                 <option value="n">Dado de Alta</option>

                                                      </select>
                                                  <br>
                                                            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                                                  </div>
                                            </div>





                                                <div class="form-group">
                                                    <div class="col-lg-offset-2 col-lg-10">
                                                        <button class="btn btn-success waves-effect waves-light" type="submit">Buscar</button>

                                                    </div>
                                                </div>
                                            </form>
                                        </div> <!-- .form -->
                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->


                        <!-- Form-validation -->
                        <div class="row">

                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Datos del Ingreso Hospitalario</h3></div>
                                    <div class="panel-body">

                                        {% if ingreso%}
                                    <table class="table">
                                      <thead>
                                        <tr>
                                           <th scope="col">Nombre del Paciente</th>
                                          <th scope="col">Fecha de Ingreso Hopitalario</th>
                                          <th scope="col">Doctor Encargado</th>
                                            <th scope="col">Tipo de ingreso</th>
                                            <th scope="col">Opciones</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      {% for ingresos in ingreso %}
                                        <tr>
                                         <th scope="row">{{ ingresos.id_paciente.id_persona.nombre}} {{ ingresos.id_paciente.id_persona.apellido}}</th>
                                         <td>{{ ingresos.fecha_ingreso}}</td>
                                         <td>{{ ingresos.id_medico.id_persona.nombre}} {{ ingresos.id_medico.id_persona.apellido}}</td>
                                            <td>{{ ingresos.id_catalogo.catalogo}}</td>
                                         <td>
                                                      {% ifequal ingresos.activo 's'%}
                                                        <a href="{% url 'app:detalleIngresoHospitalario' ingresos.id_ingresohospitalario2 %}" ><span class="label label-success">ver</span></a>
                                                        <a href="{% url 'app:EditarIngresoHospitalario' ingresos.id_ingresohospitalario2%}"><span class="label label-warning">Editar</span></a>
                                                        <a href="{% url 'app:AltaMedica' ingresos.id_ingresohospitalario2 %}" onclick="return confirm('¿Desea Dar de Alta al Pacietne?')"><span class="label label-danger">Alta Médica</span></a>
                                                      {% else %}
                                                          <a href="{% url 'app:detalleIngresoHospitalario' ingresos.id_ingresohospitalario2 %}" ><span class="label label-success">ver</span></a>
                                                      {% endifequal %}


                                         </td>
    </tr>
                                      {% endfor %}

  </tbody>
</table>
                                        {% else %}
                                                              <table class="table">
                                      <thead>
                                        <tr>
                                          <th scope="col">Nombre del Paciente</th>
                                          <th scope="col">Fecha de Ingreso Hopitalario</th>
                                          <th scope="col">Doctor Encargado</th>
                                            <th scope="col">Tipo de ingreso</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                         <th scope="row">No hay registros</th>


                                        </tr>

                                       </tbody>
                                </table>




                                        {% endif %}

                                        </div> <!-- .form -->

                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->



            </div> <!-- container -->

                </div> <!-- content -->



            </div>


{% endblock %}

app/templates/app/ingresoHospitalario/ListarServicioHospitalario.html
{% extends "app/base_template.html" %}


{% block content %}


    <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="pull-left page-title">Listar Servicios Hospitalarios </h4>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Servicios Hospitalario</h3></div>
                                    <div class="panel-body">
                                        <div class=" form">
                                            <form class="cmxform form-horizontal tasi-form"  method="POST" action="{% url 'app:listarServicioHospitalario' %}" >
                                                {% csrf_token %}
                                                <div class="form-group ">
                                                    <label for="hpaciente" class="control-label col-lg-2">Expediente del Paciente:</label>
                                                    <div class="col-lg-10">
                                                        <input  class="form-control"  id="hpaciente" name="hpaciente" type="text" maxlength="25" required>
                                                    <br>
                                                         {% if error_message %}<p ><strong ><h3 class="label label-danger" >{{ error_message }}</h3></strong></p>{% endif %}
                                                    </div>
                                                </div>


                                                <div class="form-group">
                                                    <div class="col-lg-offset-2 col-lg-10">
                                                        <button class="btn btn-success waves-effect waves-light" type="submit">Buscar</button>

                                                    </div>
                                                </div>
                                            </form>
                                        </div> <!-- .form -->
                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->


                        <!-- Form-validation -->
                        <div class="row">

                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><h3 class="panel-title">Datos del Ingreso Hospitalario</h3></div>
                                    <div class="panel-body">

                                        {% if servicio%}
                                    <table class="table">
                                      <thead>
                                        <tr>
                                           <th scope="col">Nombre del Paciente</th>
                                          <th scope="col">Responsable</th>
                                          <th scope="col">Servicio Hospitalario</th>
                                            <th scope="col">Fecha Inicio</th>
                                            <th scope="col">Duracion</th>
                                            <th scope="col">Dosis</th>
                                            <th scope="col">Opciones</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      {% for servicios in servicio %}
                                        <tr>
                                        <th scope="row">{{ servicios.id_ingresohospitalario2.id_paciente.id_persona.nombre}} {{ servicios.id_ingresohospitalario2.id_paciente.id_persona.apellido}}</th>
                                         <td>{{ servicios.id_persona.nombre}} {{ servicios.id_persona.apellido}}</td>
                                         <td>{{ servicios.id_catalogo.catalogo}} </td>
                                            <td>{{ servicios.fecha_inicio}}</td>
                                        <td>{{ servicios.duracion}}</td>
                                        <td>{{ servicios.dosis}}</td>

                                         <td>

                                                        <a href="{% url 'app:bitacoraIndex' servicios.id_servicio_hospitalario%}"><span class="label label-primary">Registro diario</span></a>
                                                        <a href="{% url 'app:editarServicioHospitalario' servicios.id_servicio_hospitalario%}"><span class="label label-warning">Editar</span></a>
                                                        <a href="{% url 'app:eliminarServicioHospitalario' servicios.id_servicio_hospitalario%}" onclick="return confirm('¿Desea Eliminar el Servicio Hospitalario?')"><span class="label label-danger">Eliminar</span></a>




                                         </td>
                                     </tr>
                                      {% endfor %}


  </tbody>
</table>
                                        {% else %}
                                                              <table class="table">
                                      <thead>
                                        <tr>
                                          <th scope="col">Nombre del Paciente</th>
                                          <th scope="col">Responsable</th>
                                          <th scope="col">Servicio Hospitalario</th>
                                            <th scope="col">Fecha Inicio</th>
                                            <th scope="col">Duracion</th>
                                            <th scope="col">Dosis</th>
                                            <th scope="col">Opciones</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                         <th scope="row">No hay registros</th>


                                        </tr>

                                       </tbody>
                                </table>




                                        {% endif %}

                                        </div> <!-- .form -->

                                    </div> <!-- panel-body -->
                                </div> <!-- panel -->
                            </div> <!-- col -->

                        </div> <!-- End row -->



            </div> <!-- container -->

                </div> <!-- content -->



            </div>


{% endblock %}